[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dexie.py"
version = "0.0.1"
authors = [
    { name="Joseph Chiocchi", email="joe@yolk.cc" },
]
description = "A simple Dexie.Space API client"
dependencies = [
    "uplink",
    "base58",
]
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3 :: Only",
]

[project.urls]
"Homepage" = "https://github.com/yyolk/dexie.py"
"Bug Tracker" = "https://github.com/yyolk/dexie.py/issues"
